#!/bin/bash

if [ "$1" == "--wrap-socket" ]
then
	target_host="127.0.0.1"
	target_port="${2##*:}"

	# print HTTP header
	printf 'HTTP/1.1 200\r\n'
	printf 'Content-Type: text/plain\r\n'
	printf 'Connection: close\r\n'
	printf '\r\n'

	# consume HTTP header, and interpret content-length, and close input after content-length is provided

	exec socat - tcp:"$target_host":"$target_port"
fi

wg_interface="${1%%:*}"
bind_port="${1##*:}"

read -r target_port < <(wg show "$wg_interface" listen-port)

echo "Wrapping http://localhost:$bind_port to wg-server@$wg_interface at 127.0.0.1:$target_port"

socat tcp-listen:"$bind_port",reuseaddr,fork system:"$0 --wrap-socket \":$target_port\""
